CREATE OR REPLACE TRIGGER TRG_UPDATE_ACTUAL_AMOUNT
AFTER INSERT OR UPDATE ON TB_TRANSACTION
                           FOR EACH ROW
DECLARE
    v_category_id TB_BUDGET.CATEGORY_ID%TYPE;
BEGIN
    -- 트랜잭션이 "지출"인 경우에만 업데이트 수행
    IF :NEW.TRANSACTION_TYPE = 1 THEN -- TRANSACTION_TYPE이 1인 경우를 지출로 가정
    -- 해당 카테고리와 일치하는 TB_BUDGET의 ACTUAL_AMOUNT를 업데이트
        UPDATE TB_BUDGET
        SET ACTUAL_AMOUNT = ACTUAL_AMOUNT + :NEW.TRANSACTION_AMOUNT
        WHERE FAMILY_ID = (SELECT FAMILY_ID FROM TB_USERS WHERE USER_NO = :NEW.USER_NO)
          AND CATEGORY_ID = :NEW.TRANSACTION_CATEGORY
          AND EXTRACT(MONTH FROM START_DATE) = EXTRACT(MONTH FROM :NEW.TRANSACTION_DATE)
          AND EXTRACT(YEAR FROM START_DATE) = EXTRACT(YEAR FROM :NEW.TRANSACTION_DATE);
    END IF;
END;
/
