/*
 * 유저
 */
INSERT INTO INSURANCE.TB_USERS (USER_NO, USER_NAME, USER_ID, USER_PW, USER_GENDER, USER_EMAIL, USER_PHONE_NO, USER_ADDRESS, USER_RESIDENT_ID, USER_STATUS, USER_BIRTH, USER_REGISTER_DT, FAMILY_ID)
VALUES (1, '김철수', 'kim', 'qq', '남성', 'kimcs@example.com', '010-1234-5678', '서울시 강남구 테헤란로 123', '800101-1234567', 'ACTIVE', TO_DATE('1980-01-01', 'YYYY-MM-DD'), SYSDATE, null);

INSERT INTO INSURANCE.TB_USERS (USER_NO, USER_NAME, USER_ID, USER_PW, USER_GENDER, USER_EMAIL, USER_PHONE_NO, USER_ADDRESS, USER_RESIDENT_ID, USER_STATUS, USER_BIRTH, USER_REGISTER_DT, FAMILY_ID)
VALUES (2, '이영희', 'lee', 'qq', '여성', 'leeyh@example.com', '010-1122-3344', '서울시 서초구 서초대로 456', '850505-2345678', 'ACTIVE', TO_DATE('1985-05-05', 'YYYY-MM-DD'), SYSDATE, null);


/*
 * 보험
 */
INSERT INTO TB_INSURANCE (INSURANCE_ID, INSURANCE_TYPE, INSURANCE_AMOUNT, INSURANCE_START_DATE, INSURANCE_END_DATE, INSURANCE_TERM, INSURANCE_STATE, INSURANCE_RENEWAL, INSURANCE_PAYMENT_TYPE, INSURANCE_PAYMENT_CYCLE, INSURANCE_PAYMENT_TOTAL, INSURANCE_PAYMENT_DATE, USER_NO, INSURANCE_CODE, INSURANCE_NAME, INSURANCE_ACCOUNT, INSURANCE_COMPANY, INSURANCE_MONTHLY_PAYMENT)
VALUES ('INS-789012', '생명보험', 100000000, SYSDATE - 365, SYSDATE + 3650, 10, 1, 'YES', '자동이체', '월', 12000000, SYSDATE + 30, 1, 'INS001', '김철수의 생명보험', '110-123-456789', '하나생명', 100000);
